#<><><><><><><><><><><><><><><><><><>
#GhostRider CAS version
#2025-03-04 01.17pm
#<><><><><><><><><><><><><><><><><><>

#This part contains the IP address and port of the Guanzon's API Server
#<><><><><><><><><><><><><><><><><><>
sys.webhost.ip=
sys.webhost.port= 
#<><><><><><><><><><><><><><><><><><>

#This part contains the configuration for product
#Format: sys.<product>.<config>=value
#gRider configuration 
#<><><><><><><><><><><><><><><><><><>
sys.gRider.UserName=77FE761B6CB8CCF60A1FA5D02A4D83A5
sys.gRider.Password=0F3DF529201885A6531F730120593059
sys.gRider.ClientID=GGC_BGK01
sys.gRider.ServerName=localhost
sys.gRider.Database=GCASys_DBF
sys.gRider.Port=3306
sys.gRider.ComputerID=02
sys.gRider.Industry=09
sys.gRider.Category=0007
#<><><><><><><><><><><><><><><><><><>

#gRider configuration 
#<><><><><><><><><><><><><><><><><><>
sys.IntegSys.UserName=_\u00C2
sys.IntegSys.Password=m\u00D7\u00A3\u0090"\u00CE\u00D1r\u00B8\u0017>\u00A7
sys.IntegSys.ClientID=GGC_BM001
sys.IntegSys.ServerName=localhost
sys.IntegSys.Database=GGC_ISysDBF
sys.IntegSys.Port=3306
sys.IntegSys.ComputerID=01
sys.IntegSys.Industry=01
sys.IntegSys.Category=
#<><><><><><><><><><><><><><><><><><>